name: match_band
description: "MatchBand"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6

  image_picker: ^1.1.2
  http: ^1.2.1
  file_picker: ^8.0.5
  webview_flutter: ^4.8.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: true
  ios: false

  web:
    generate: true

  image_path: "assets/icon/app_icon.png"

  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#121212"
  image: assets/icon/app_icon.png

  android: true
  ios: false
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png