// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcte-6Z-ya9oQRyTFNYYDED1iwWvfwSSQ',
    appId: '1:38909991505:web:63cb0c8bd8bfe01680b670',
    messagingSenderId: '38909991505',
    projectId: 'matchband-app',
    authDomain: 'matchband-app.firebaseapp.com',
    storageBucket: 'matchband-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRO8TVFG-KIt8_U5qRSkNS6kGE-G51Uc',
    appId: '1:38909991505:android:22b4acba3950bc4680b670',
    messagingSenderId: '38909991505',
    projectId: 'matchband-app',
    storageBucket: 'matchband-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBagnY7zuqaD6SebzX7IFoMEDaB8qons1M',
    appId: '1:38909991505:ios:fc968fcd4885fc0780b670',
    messagingSenderId: '38909991505',
    projectId: 'matchband-app',
    storageBucket: 'matchband-app.firebasestorage.app',
    iosBundleId: 'com.matchband.app.matchBand',
  );
}
